"""Map workflow-fetched + hand-entered competition decklists onto EN_Card_Data.csv ids,
substitute the few special energies absent from our set, keep the lists that reach a legal
60, and WRITE them to rl/decks_meta.py as the real-deck training pool.

  PYTHONPATH=. python scripts/map_fetched.py <workflow_output.json>
"""
from __future__ import annotations
import json
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from map_decks import load_names, norm, DECKS as HAND_DECKS  # hand-entered (lucario/gardevoir) + index

ENERGY_CODE = {"grass": "g", "fire": "r", "water": "w", "lightning": "l", "psychic": "p",
               "fighting": "f", "darkness": "d", "dark": "d", "metal": "m"}
# special energies absent from our set -> substitute the basic energy they mainly provide
SPECIAL_ENERGY_SUB = {"telepathic psychic energy": "p"}


def _basic(code, name2ids):
    for cand in (f"basic {{{code}}} energy", f"basic {code} energy"):
        if cand in name2ids:
            return name2ids[cand][0]
    return None


def resolve(name, name2ids):
    n = norm(name)
    if n in name2ids:
        return name2ids[n][0]
    base = n.replace("basic ", "").replace(" energy", "").strip()
    if base in ENERGY_CODE:
        r = _basic(ENERGY_CODE[base], name2ids)
        if r is not None:
            return r
    if n in SPECIAL_ENERGY_SUB:                      # special energy -> basic substitute
        r = _basic(SPECIAL_ENERGY_SUB[n], name2ids)
        if r is not None:
            return r
    if "(" in n:                                     # "Bouffalant (Stellar Crown)" -> "bouffalant"
        b = n.split("(")[0].strip()
        if b in name2ids:
            return name2ids[b][0]
    hits = [v[0] for k, v in name2ids.items() if len(n) > 5 and n in k]
    return hits[0] if len(set(hits)) == 1 else None


def build(cards, name2ids):
    """cards: list of (name, count). Returns (ids, missing)."""
    ids, missing = [], []
    for name, cnt in cards:
        r = resolve(name, name2ids)
        if r is not None:
            ids += [r] * cnt
        else:
            missing.append(f"{name} x{cnt}")
    return ids, missing


def main():
    name2ids = load_names()
    fetched = json.load(open(sys.argv[1], encoding="utf-8"))["result"]["all"]

    candidates = {}  # name -> list[(cardname, count)]
    for d in fetched:
        if d.get("found"):
            key = "meta_" + norm(d["archetype"]).split("(")[0].strip().replace(" ", "_")
            candidates[key] = [(c["name"], c["count"]) for c in d["cards"]]
    # hand-entered real lists (2 lucario map 60/60; gardevoir ones are pre-rotation/gappy)
    for k, spec in HAND_DECKS.items():
        candidates[k] = list(spec.items())

    built, gappy = {}, []
    for key, cards in candidates.items():
        ids, missing = build(cards, name2ids)
        if not missing and len(ids) == 60:
            built[key] = ids
        else:
            gappy.append((key, len(ids), missing))

    with open("rl/decks_meta.py", "w", encoding="utf-8") as f:
        f.write('"""Real competition decks (Mega-Evolution Standard) mapped to our card ids.\n')
        f.write('Auto-generated by scripts/map_fetched.py from verified Limitless lists.\n')
        f.write('Telepathic Psychic Energy (absent from our set) substituted with basic Psychic.\n"""\n\n')
        f.write("META = {\n")
        for k, ids in built.items():
            f.write(f"    {k!r}: {ids},\n")
        f.write("}\n")
        f.write("\ntry:                       # fold in episode-mined Kaggle decks (incl. Crustle)\n"
                "    from .decks_kaggle import KAGGLE_DECKS as _K\n    META.update(_K)\n"
                "except Exception:\n    pass\n")

    print(f"BUILT {len(built)} real decks -> rl/decks_meta.py:")
    for k in built:
        print(f"   60/60  {k}")
    print(f"\nSKIPPED {len(gappy)} (key cards/staples not in our set):")
    for k, n, miss in sorted(gappy, key=lambda x: x[1], reverse=True):
        print(f"   {n}/60  {k}: {'; '.join(miss[:5])}{' ...' if len(miss) > 5 else ''}")


if __name__ == "__main__":
    main()
